In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df=pd.read_csv('/content/sonar_dataset.csv',header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [9]:
df.shape

(208, 61)

In [10]:
df.isna().sum().sum()

0

In [11]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [12]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [13]:
X=df.drop(60,axis=1)
y=df[60]

In [14]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [15]:
y = pd.get_dummies(y, drop_first=True)
y

R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]

In [16]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [17]:
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [20]:
X_train.shape

(166, 60)

In [19]:
import tensorflow as tf
from tensorflow import keras

In [21]:
model=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')

])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
model.fit(X_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
21/21 [==============================] - 1s 3ms/step - loss: 0.7001 - accuracy: 0.4699
Epoch 2/100
21/21 [==============================] - 0s 2ms/step - loss: 0.6738 - accuracy: 0.7289
Epoch 3/100
21/21 [==============================] - 0s 2ms/step - loss: 0.6584 - accuracy: 0.6988
Epoch 4/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6368 - accuracy: 0.7590
Epoch 5/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6084 - accuracy: 0.7590
Epoch 6/100
21/21 [==============================] - 0s 3ms/step - loss: 0.5715 - accuracy: 0.8193
Epoch 7/100
21/21 [==============================] - 0s 3ms/step - loss: 0.5344 - accuracy: 0.7590
Epoch 8/100
21/21 [==============================] - 0s 2ms/step - loss: 0.4952 - accuracy: 0.8072
Epoch 9/100
21/21 [==============================] - 0s 2ms/step - loss: 0.4712 - accuracy: 0.8133
Epoch 10/100
21/21 [==============================] - 0s 2ms/step - loss: 0.4203 - accuracy: 0.8434
Epoch 11/

In [23]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 8ms/step - loss: 1.3527 - accuracy: 0.7143


[1.3527319431304932, 0.7142857313156128]

In [24]:
y_pred=model.predict(X_test).reshape(-1)
y_pred[:10]

2/2 [==============================] - 0s 12ms/step


array([3.7450338e-06, 9.9777067e-01, 9.9574733e-01, 1.2985502e-04,
       1.0000000e+00, 9.9726474e-01, 1.2273078e-01, 9.9999994e-01,
       1.8928757e-04, 1.0000000e+00], dtype=float32)

In [27]:
y_pred=np.round(y_pred)
print(y_pred[:10])

[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [28]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [29]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.80      0.73        20
           1       0.78      0.64      0.70        22

    accuracy                           0.71        42
   macro avg       0.72      0.72      0.71        42
weighted avg       0.72      0.71      0.71        42



In [66]:
modelid=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dropout(0.60),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dropout(0.55),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dropout(0.55),
    keras.layers.Dense(1,activation='sigmoid')

])
modelid.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [67]:
modelid.fit(X_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
21/21 [==============================] - 1s 3ms/step - loss: 0.7440 - accuracy: 0.4277
Epoch 2/100
21/21 [==============================] - 0s 3ms/step - loss: 0.7192 - accuracy: 0.5181
Epoch 3/100
21/21 [==============================] - 0s 3ms/step - loss: 0.7266 - accuracy: 0.4759
Epoch 4/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6863 - accuracy: 0.5422
Epoch 5/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6979 - accuracy: 0.5723
Epoch 6/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6917 - accuracy: 0.4940
Epoch 7/100
21/21 [==============================] - 0s 2ms/step - loss: 0.7144 - accuracy: 0.4699
Epoch 8/100
21/21 [==============================] - 0s 2ms/step - loss: 0.6962 - accuracy: 0.5000
Epoch 9/100
21/21 [==============================] - 0s 2ms/step - loss: 0.7037 - accuracy: 0.5422
Epoch 10/100
21/21 [==============================] - 0s 2ms/step - loss: 0.6936 - accuracy: 0.5361
Epoch 11/

In [68]:
modelid.evaluate(X_test,y_test)

2/2 [==============================] - 0s 10ms/step - loss: 0.4084 - accuracy: 0.8095


[0.40841934084892273, 0.8095238208770752]

In [69]:
y_pred=modelid.predict(X_test).reshape(-1)
y_pred

2/2 [==============================] - 0s 5ms/step


array([5.1645609e-04, 7.7794605e-01, 7.9691577e-01, 3.1308670e-02,
       9.2815340e-01, 7.9928869e-01, 5.1024175e-01, 9.5476502e-01,
       4.7525153e-02, 9.4126248e-01, 5.9500611e-01, 5.6875008e-01,
       3.8258165e-01, 8.6502977e-02, 4.2852983e-01, 4.0577558e-01,
       8.4352362e-01, 2.7987175e-02, 5.6577748e-01, 9.0546799e-01,
       3.0098388e-02, 9.2088991e-01, 1.3126718e-01, 7.4059480e-01,
       2.9859847e-01, 7.8714401e-02, 4.6256524e-01, 2.9973185e-01,
       9.2592353e-01, 8.7756209e-02, 7.2997308e-01, 7.2048237e-03,
       4.0941119e-01, 8.1895667e-01, 8.0900353e-01, 7.5614178e-01,
       9.2320019e-01, 7.4368089e-01, 8.5201484e-01, 3.0065006e-01,
       1.9790393e-01, 1.8989606e-01], dtype=float32)

In [70]:
y_pred=np.round(y_pred)
y_pred[:10]

array([0., 1., 1., 0., 1., 1., 1., 1., 0., 1.], dtype=float32)

In [71]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [72]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80        20
           1       0.82      0.82      0.82        22

    accuracy                           0.81        42
   macro avg       0.81      0.81      0.81        42
weighted avg       0.81      0.81      0.81        42

